name: CI-CD to Tomcat

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Build with Maven
      - name: Build with Maven
        run: mvn package

      # 4. Deploy to Tomcat
      - name: Deploy WAR to Tomcat
        env:
          TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
          TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
        run: |
          curl -u $TOMCAT_USER:$TOMCAT_PASSWORD \
               -T webapp/target/webapp.war \
               http://35.89.249.207:8081/manager/text/deploy?path=/webapp&update=true
